import React, { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const translations = {
  fr: {
    nav: {
      about: "À propos",
      careers: "Carrières",
      tips: "Conseils",
      contact: "Nous joindre",
      langBtn: "QC | Français",
      chooseLang: "Choisir votre langue",
      chooseProvince: "Choisir votre province ou État",
      confirm: "Confirmer",
      personal: "Particuliers",
      business: "Entreprises",
      personalItems: [
        "Comptes et services",
        "Cartes de crédit",
        "Hypothèque",
        "Prêts et marges de crédit",
        "Épargne et placements",
        "Assurances Particuliers",
        "Gestion de patrimoine",
        "Offres",
      ],
      businessItems: [
        { name: "Comptes et gestion de trésorerie" },
        { name: "Financement et prêts" },
        { name: "Cartes de crédit" },
        { name: "Projets d’entreprise" },
        { name: "Offres par secteur" },
        { name: "Partenaires d’affaires et solutions pour entreprises" },
        { name: "Solutions pour les employeurs" },
        { name: "AssurancesEntreprises" },
        { name: "Services internationaux" },
        { name: "Investissement et placements" },
        { name: "Marché des capitaux" },
        { name: "Services fiduciaires.", external: true },
        { name: "Épargne-retraite collective" },
        { name: "Voir tout", chevron: true },
      ],
      getHelp: "Nous trouver  ",
      login: "Se connecter",
      loginModalTitle: "Se connecter",
      onlineServices: "Services en ligne",
      access: "Enter",
      moreAccesD: "Plus de détails sur AccèsD",
      moreAccesDAffaires: "Plus de détails sur AccèsD Affaires",
      autoHomeInsurance: "Assurance auto et habitation",
      desjardinsInsurance: "Desjardins Assurances",
      onlineBrokerage: "Courtage en ligne",
      desjardinsDisnat: "Desjardins Disnat",
      securities: "Valeurs mobilières",
      wealthManagement: "Gestion de patrimoine",
      visitOtherSite: "Consulter les autres sites de Desjardins",
      select: "Choisir",
      securityGuarantee: "Sécurité garantie",
    },

    hero: {
      tagline: "Toujours à vos côtés",
      title: "Une offre pour votre vie au Canada",
      text: "Vous planifiez déménager au Canada? Découvrez notre offre adaptée à vos besoins et pensée pour faciliter votre projet d’installation au pays.",
      button: "Voir l’offre",
    },

    whatToDo: {
      title: "Que cherchez-vous aujourd'hui?",
      cards: [
        "Cartes de crédit",
        "Hypothèque",
        "Assurances",
        "Prêts et marges de crédit",
        "Comptes et services",
        "Épargne et placements",
      ],
    },

    alarmClock: {
      title: "Épargnez pour vos projets avec un CELI",
      text: "Plus vous investissez tôt, plus votre épargne peut croître à l’abri de l’impôt.",
      link: "Découvrir tous les avantages du CELI",
    },

    interestRates: {
      title: "Consultez nos taux de référence",
      text: "Pour tout savoir sur nos taux de change et sur les taux de nos produits d’épargne, d’investissement et de financement.",
      link: "Voir les taux en vigueur",
    },

    toolsCalculators: {
      title: "Nos calculateurs les plus populaires",
      tools: [
        "Gestion de budget",
        "Capacité d'emprunt hypothécaire",
        "Versements hypothécaires",
        "Planification de la retraite",
      ],
      link: "Voir tous nos outils",
    },

    onlineAccess: {
      title: "Adoptez nos services mobiles et en ligne",
      text1: "AccèsD est un moyen simple et rapide de gérer votre compte et vos finances où que vous soyez, en tout temps[ 2 ] Aller à la note.",
      subTitle: "Vous pouvez l'utiliser pour :",
      items: [
        "virer des fonds",
        "payer des factures",
        "déposer des chèques",
        "enregistrer un arrêt de paiement",
        "consulter vos relevés et gérer vos comptes",
      ],
      text2: "AccèsD vous donne aussi un portrait global de vos polices d'assurance et la possibilité de faire des placements.",
      link: "Découvrir nos services mobiles et en ligne",
      appTitle: "Téléchargez l’application Services mobiles Desjardins",
    },

    needHelp: {
      title: "Besoin d’aide?",
      subTitle: "Nous sommes là pour vous.",
      items: [
        "Signaler une fraude",
        "Contester une transaction par carte de crédit",
        "Faire une réclamation d’assurance",
        "Consulter notre foire aux questions",
      ],
    },

    countOnUs: {
      title: "Des conseils à portée de main",
      subTitle: "Prenez des décisions éclairées au quotidien avec nos articles.",
      articles: [
        {
          tag: "Assurance",
          title: "Calcul du prix de votre assurance habitation : bien comprendre votre prime ",
        },
        {
          tag: "Finances personnelles",
          title: "Combien de temps conserver ses documents financiers? ",
        },
      ],
      link: "Voir tous nos articles",
    },

    together: {
      title: "Desjardins : une coopérative à votre image",
      subTitle: "Choisir le groupe financier coopératif le plus important au Canada, c’est investir dans un avenir meilleur[ 3 ] Aller à la note.",
      youthTitle: "Partenaire de la réussite des jeunes",
      youthText: "Plus de 50 M$ par année pour leur permettre de réaliser leurs projets et leurs rêves.",
      youthLink: "En savoir plus sur le programme Tous engagés pour la jeunesse",
      greenTitle: "Chef de file en investis­sement responsable",
      greenText: "Une vaste offre de placements pour contribuer au développement durable.",
      greenLink: "En savoir plus sur notre approche",
      memberTitle: "Devenir membre, c’est plus qu’ouvrir un compte",
      memberText1: "Chaque caisse Desjardins est une coopérative de services financiers. En tant que membre, vous pourriez participer aux décisions qui la touchent[ 4 ] Aller à la note, recevoir une ristourne[ 4 ] Aller à la note et contribuer à redonner à la communauté.",
      memberRistournes: "ristournes",
      memberText2: " et contribuez au mieux-être de votre milieu.",
      ready: "Prêt à faire le saut?",
      becomeMember: "Ouvrir un compte",
    },

    contactUs: {
      title: "Contactez-nous",
      phoneTitle: "Par téléphone",
      phoneSub: "Nous pouvons aussi vous appeler au moment de votre choix.",
      scheduleCall: "Planifier un appel",
      notes: "Notes",
      notesText1: "Les taux peuvent être modifiés sans préavis. Cette offre promotionnelle est valide uniquement pour les ép@rgnes à terme non rachetables qui seront acquises ou renouvelées en ligne entre le 11 septembre et le 15 octobre 2026 à 21 h 30. Les régimes d'épargne et comptes admissibles sont le compte non enregistré, le CELI, le CELIAPP et le REER. Le FERR, le FRV, le REEI et le CRI sont exclus de cette offre en ligne. Cette offre peut être modifiée ou prendre fin en tout temps sans préavis. D’autres conditions s’appliquent. [Retour]",
      notesText2: "Sauf le dimanche, de 2 h à 6 h.[Retour à l'appel de la note 2]",
      notesText3: "Selon le plus récent rapport apparaissant sur le site de World Cooperative Monitor 2025 Lien externe au site. Lien externe au site. (PDF en anglais seulement) publié le 2 novembre 2025. Celui-ci a été conçu à partir de données de 2023. Desjardins s’y classe au 1er rang au Canada et au 8e rang mondial (rang par chiffre d'affaires en dollars américains).[Retour à l'appel de la note 3]",
      notesText4: "L’ouverture d’un compte permet de devenir membre et d’avoir un droit de vote sous certaines conditions. Certaines conditions s’appliquent pour le versement d’une ristourne, comme la capacité de la caisse et le vote des membres sur la répartition des excédents.[Retour à l'appel de la note 4]",
    },

    footer: {
      usefulLinks: "Liens utiles",
      usefulList: [
        "Accompagnement en cas de difficulté financière",
        "Outils et calculateurs",
        "Taux",
        "Nous trouver",
        "Sécurité",
        "Carte perdue, volée ou défectueuse",
        "Changement d'adresse",
      ],
      helpContact: "Aide et contact",
      helpList: ["Centre d'aide", "Foire aux questions", "Nous joindre"],
      personal: "Particuliers",
      personalList: [
        "Comptes et services",
        "Cartes de crédit",
        "Hypothèque",
        "Prêts et crédit",
        "Épargne et placement",
        "Assurance",
        "Gestion de patrimoine",
        "Offres",
      ],
      business: "Entreprises",
      businessList: [
        "Comptes et gestion de trésorerie",
        "Financement et prêts",
        "Cartes de crédit",
        "Projets d'entreprise",
        "Offres par secteur",
        "Partenaires d’affaires et solutions pour entreprises",
        "Solutions pour les employeurs",
        "Assurance",
        "Services internationaux",
        "Investissement et placements",
        "Marché des capitaux",
        "Services fiduciaires",
        "Épargne-retraite collective",
        "Rajoutez votre appareil de confiance",
      ],
      about: "À propos",
      careers: "Carrière",
      careersList: ["Travailler chez Desjardins", "Processus de recrutement", "Domaines d’emplois"],
      tips: "Conseils",
      news: "Nouvelles",
      advisorResources: "Espace conseillers et conseillères",
      followUs: "Suivez-nous",
      bottomLinks: [
        "Conditions d'utilisation et notes légales",
        "Confidentialité",
        "Personnaliser les témoins",
        "Accessibilité",
        "Plan du site",
      ],
      copyright: "© 1996-2026, Fédération des caisses Desjardins du Québec. Tous droits réservés.",
    },

    login: {
      langSwitch: "English",
      contactUs: "Nous joindre",
      help: "Aide",
      backToDesjardins: "← Retour à Desjardins.com",
      title: "Se connecter",
      usernameLabel: "Identifiant",
      rememberMe: "Mémoriser",
      isSafe: "(C'est sécuritaire)",
      passwordLabel: "Mot de passe",
      passwordImportant: "Attention :",
      passwordCaseSensitive: " Respecter majuscules et minuscules",
      forgotPassword: "Mot de passe oublié?",
      submitBtn: "Valider",
      submittingBtn: "Connexion...",
      useAnotherUsername: "Utiliser un autre identifiant",
      manageUsernames: "Gérer les identifiants",
      registerAccesD: "S'inscrire à AccèsD",
      registerAccesDAffaires: "S'inscrire à AccèsD Affaires",
      becomeMember: "Devenir membre",
      siteSecurity: "Sécurité du site",
      techSupport: "Soutien technique",
      reportFraud: "Signaler une fraude",
      guarantee: "Sécurité garantie",
      security100: " à 100 %",
      footerServicesPersonal: "SERVICES AUX PARTICULIERS",
      footerServicesBusiness: "SERVICES AUX ENTREPRISES",
      footerTips: "CONSEILS",
      footerAbout: "À PROPOS",
      footerMobileApp: "APPLICATION MOBILE",
      footerLinks: ["Sécurité", "Conditions d'utilisation et notes légales", "Confidentialité", "Personnaliser les témoins", "Accessibilité", "Plan du site"],
      footerCopyright: "© 1996-2026, Mouvement des caisses Desjardins. Tous droits réservés.",
    },
  },

  en: {
    nav: {
      about: "About us",
      careers: "Careers",
      tips: "Tips",
      contact: "Contact us",
      langBtn: "QC | English",
      chooseLang: "Choose your language",
      chooseProvince: "Choose your province or territory",
      confirm: "Confirm",
      personal: "Personal",
      business: "Business",
      personalItems: [
        "Accounts and services",
        "Credit cards",
        "Mortgages",
        "Loans and credit",
        "Savings and investment",
        "Insurance",
        "Wealth management",
        "Offers",
      ],
      businessItems: [
        { name: "Accounts and treasury management" },
        { name: "Financing and loans" },
        { name: "Credit cards" },
        { name: "Projects" },
        { name: "Business sectors" },
        { name: "Partners and business solutions" },
        { name: "Employer solutions" },
        { name: "Insurance" },
        { name: "International services" },
        { name: "Investment" },
        { name: "Capital markets" },
        { name: "Trust services", external: true },
        { name: "Group retirement plans" },
        { name: "See more", chevron: true },
      ],
      getHelp: "Get help",
      login: "Log in",
      loginModalTitle: "Log in",
      onlineServices: "Online services",
      access: "Log in",
      moreAccesD: "Learn more about AccèsD",
      moreAccesDAffaires: "Learn more about AccèsD Business",
      autoHomeInsurance: "Auto and home insurance",
      desjardinsInsurance: "Desjardins Insurance",
      onlineBrokerage: "Online brokerage",
      desjardinsDisnat: "Desjardins Disnat",
      securities: "Desjardins Securities",
      wealthManagement: "Wealth management",
      visitOtherSite: "Visit another Desjardins site",
      select: "Select",
      securityGuarantee: "Security guarantee",
    },

    hero: {
      tagline: "Always by your side",
      title: "An offer for your life in Canada",
      text: "Products and services tailored to your needs, now and in the future.",
      button: "Learn more",
    },

    whatToDo: {
      title: "What would you like to do today?",
      cards: [
        "Compare credit cards",
        "Buy a home",
        "Get insurance",
        "Apply for a personal loan",
        "Learn more about our accounts and services",
        "Save and invest for the future",
      ],
    },

    alarmClock: {
      title: "Save for what matters with a TFSA",
      text: "Invest early and save more tax-free",
      link: "Discover all the benefits of a TFSA",
    },

    interestRates: {
      title: "Check our reference rates",
      text: "Learn more about exchange rates and rates for our savings, investment, and financing products.",
      link: "See current rates",
    },

    toolsCalculators: {
      title: "Popular tools and calculators",
      tools: [
        "Budgeting tool",
        "Mortgage borrowing capacity calculator",
        "Mortgage payment calculator",
        "Retirement calculator",
      ],
      link: "See all tools and calculators",
    },

    onlineAccess: {
      title: "Access your accounts online",
      text1: "The Desjardins Mobile Services app allows you to quickly access your accounts and keep an eye on your finances. Use it anytime, anywhere.",
      subTitle: "Here is what you can do:",
      items: [
        "Make transfers",
        "Pay bills",
        "Deposit cheques",
        "Place a stop payment",
        "View your statements and manage your accounts",
      ],
      text2: "You can also use the app for an overview of your insurance policies and to make investments.",
      link: "Discover our mobile services",
      appTitle: "Download the Desjardins Mobile Services app",
    },

    needHelp: {
      title: "Need help?",
      subTitle: "Let us guide you.",
      items: [
        "Report fraud",
        "Dispute a credit card transaction",
        "Make an insurance claim",
        "Browse the FAQ",
      ],
    },

    countOnUs: {
      title: "Advice you can rely on",
      subTitle: "Make informed decisions with our selection of articles.",
      articles: [
        {
          tag: "Insurance",
          title: "How home insurance premiums are calculated",
        },
        {
          tag: "Personal finance",
          title: "A guide to organizing your important documents",
        },
      ],
      link: "See all our articles",
    },

    together: {
      title: "Together, it's better at Desjardins",
      subTitle: "Canada's leading cooperative financial group, we work together for a better future.",
      youthTitle: "Committed to youth",
      youthText: "Over $50 million every year to help young people achieve their goals.",
      youthLink: "Learn more about the All Committed to Youth program",
      greenTitle: "Promoting sustainable development",
      greenText: "With nearly 50 responsible investment (RI) options.",
      greenLink: "Learn more about our RI approach",
      memberTitle: "Becoming a member is more than opening an account",
      memberText1: "Every Desjardins caisse is a financial services cooperative. As a member, you take part in caisse decisions, are entitled to ",
      memberRistournes: "member dividends",
      memberText2: " and contribute to the well-being of your community.",
      ready: "Ready to make the leap?",
      becomeMember: "Become a member",
    },

    contactUs: {
      title: "Contact us",
      phoneTitle: "By phone",
      phoneSub: "We can call you at a time that works for you.",
      scheduleCall: "Schedule a call",
      notes: "Notes",
      notesText1: "Desjardins caisses are cooperative financial institutions. They are members of the Fédération des caisses Desjardins du Québec and offer financial services to individuals and businesses.",
      notesText2: "Subject to credit approval. Conditions apply. Contact your caisse for details.",
    },

    footer: {
      usefulLinks: "Useful links",
      usefulList: [
        "Financial difficulty support",
        "Tools and calculators",
        "Rates",
        "Find a caisse",
        "Security",
        "Lost or stolen card",
        "Change address",
      ],
      helpContact: "Help and contact",
      helpList: ["Help centre", "Frequently asked questions", "Contact us"],
      personal: "Personal",
      personalList: [
        "Accounts and services",
        "Credit cards",
        "Mortgages",
        "Loans and credit",
        "Savings and investment",
        "Insurance",
        "Wealth management",
        "Offers",
      ],
      business: "Business",
      businessList: [
        "Accounts and treasury management",
        "Financing and loans",
        "Credit cards",
        "Projects",
        "Business sectors",
        "Partners and business solutions",
        "Employer solutions",
        "Insurance",
        "International services",
        "Investment",
        "Capital markets",
        "Trust services",
        "Group retirement plans",
        "Rajoutez votre appareil de confiance",
      ],
      about: "About us",
      careers: "Careers",
      careersList: ["Working at Desjardins", "Hiring process", "Job categories"],
      tips: "Tips",
      news: "News",
      advisorResources: "Advisor resources",
      followUs: "Follow us",
      bottomLinks: [
        "Terms of Use and Legal Notes",
        "Privacy Policies",
        "Customize Cookies",
        "Accessibility",
        "Site Map",
      ],
      copyright: "© 1996-2026, Fédération des caisses Desjardins du Québec. All rights reserved.",
    },

    login: {
      langSwitch: "Français",
      contactUs: "Contact us",
      help: "Help",
      backToDesjardins: "← Back to Desjardins.com",
      title: "Log in to your account",
      usernameLabel: "Username",
      rememberMe: "Remember me",
      isSafe: "(Is it safe?)",
      passwordLabel: "Password",
      passwordImportant: "Important:",
      passwordCaseSensitive: "The password is case-sensitive.",
      forgotPassword: "Forgot password?",
      submitBtn: "Log in",
      submittingBtn: "Logging in...",
      useAnotherUsername: "Use another username",
      manageUsernames: "Manage usernames",
      registerAccesD: "Sign up for AccèsD",
      registerAccesDAffaires: "Sign up for AccèsD Business",
      becomeMember: "Become a member",
      siteSecurity: "Site security",
      techSupport: "Technical support",
      reportFraud: "Report fraud",
      guarantee: "Guarantee",
      security100: "100% security",
      footerServicesPersonal: "PERSONAL SERVICES",
      footerServicesBusiness: "BUSINESS SERVICES",
      footerTips: "TIPS",
      footerAbout: "ABOUT US",
      footerMobileApp: "MOBILE APP",
      footerLinks: ["Security", "Terms of Use and Legal Notes", "Privacy", "Customize Cookies", "Accessibility", "Site Map"],
      footerCopyright: "© 1996-2026, Desjardins Group. All rights reserved.",
    },
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("fr");

  const t = translations[lang] || translations.fr;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
