import React, { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const translations = {
  fr: {
    nav: {
      about: "À propos",
      careers: "Carrières",
      tips: "Conseils",
      contact: "Nous joindre",
      langBtn: "QC | Français",
      chooseLang: "Choisir votre langue",
      chooseProvince: "Choisir votre province ou territoire",
      confirm: "Confirmer",
      personal: "Particuliers",
      business: "Entreprises",
      personalItems: [
        "Comptes et services",
        "Cartes de crédit",
        "Hypothèque",
        "Prêts et crédit",
        "Épargne et placement",
        "Assurance",
        "Gestion de patrimoine",
        "Offres",
      ],
      businessItems: [
        { name: "Comptes et gestion de trésorerie" },
        { name: "Financement et prêts" },
        { name: "Cartes de crédit" },
        { name: "Projets" },
        { name: "Secteurs d'activité" },
        { name: "Partenaires et solutions d'affaires" },
        { name: "Solutions pour employeurs" },
        { name: "Assurance" },
        { name: "Services internationaux" },
        { name: "Placement" },
        { name: "Marchés des capitaux" },
        { name: "Services de fiducie", external: true },
        { name: "Régimes collectifs de retraite" },
        { name: "Voir plus", chevron: true },
      ],
      getHelp: "Obtenir de l'aide",
      login: "Se connecter",
      loginModalTitle: "Se connecter",
      onlineServices: "Services en ligne",
      access: "Accéder",
      moreAccesD: "En savoir plus sur AccèsD",
      moreAccesDAffaires: "En savoir plus sur AccèsD Affaires",
      autoHomeInsurance: "Assurance auto et habitation",
      desjardinsInsurance: "Desjardins Assurances",
      onlineBrokerage: "Courtage en ligne",
      desjardinsDisnat: "Desjardins Disnat",
      securities: "Valeurs mobilières Desjardins",
      wealthManagement: "Gestion de patrimoine",
      visitOtherSite: "Consulter un autre site de Desjardins",
      select: "Sélectionner",
      securityGuarantee: "Garantie de sécurité",
    },

    hero: {
      tagline: "Engagés. Connectés.",
      title: "Vous arrivez au Canada?",
      text: "Nous sommes là pour vous aider à vous installer avec des produits et services adaptés à votre réalité.",
      button: "Découvrir l'offre pour les nouveaux arrivants",
    },

    whatToDo: {
      title: "Que souhaitez-vous faire aujourd'hui?",
      cards: [
        "Comparer les cartes de crédit",
        "Acheter une maison",
        "Obtenir une assurance",
        "Faire une demande de prêt personnel",
        "En savoir plus sur nos comptes et services",
        "Épargner et investir pour l'avenir",
      ],
    },

    alarmClock: {
      title: "Épargnez pour ce qui compte avec un CELI",
      text: "Investissez tôt et épargnez davantage à l'abri de l'impôt",
      link: "Découvrir tous les avantages du CELI",
    },

    interestRates: {
      title: "Consulter nos taux de référence",
      text: "En savoir plus sur les taux de change et les taux de nos produits d'épargne, de placement et de financement.",
      link: "Voir les taux en vigueur",
    },

    toolsCalculators: {
      title: "Outils et calculateurs populaires",
      tools: [
        "Outil de budget",
        "Calculateur de capacité d'emprunt hypothécaire",
        "Calculateur de versements hypothécaires",
        "Calculateur de retraite",
      ],
      link: "Voir tous les outils et calculateurs",
    },

    onlineAccess: {
      title: "Accéder à vos comptes en ligne",
      text1: "L'application Services mobiles Desjardins vous permet d'accéder rapidement à vos comptes et de garder un œil sur vos finances. Utilisez-la en tout temps et en tout lieu.",
      subTitle: "Voici ce que vous pouvez faire :",
      items: [
        "Faire des virements",
        "Payer des factures",
        "Déposer des chèques",
        "Faire une opposition",
        "Consulter vos relevés et gérer vos comptes",
      ],
      text2: "Vous pouvez aussi accéder à l'application pour avoir une vue d'ensemble de vos polices d'assurance et faire des placements.",
      link: "Découvrir nos services mobiles",
      appTitle: "Télécharger l'application Services mobiles Desjardins",
    },

    needHelp: {
      title: "Besoin d'aide?",
      subTitle: "Laissez-nous vous guider.",
      items: [
        "Signaler une fraude",
        "Contester une transaction par carte de crédit",
        "Faire une réclamation d'assurance",
        "Consulter la FAQ",
      ],
    },

    countOnUs: {
      title: "Des conseils sur lesquels vous pouvez compter",
      subTitle: "Prenez des décisions éclairées grâce à notre sélection d'articles.",
      articles: [
        {
          tag: "Assurance",
          title: "Comment la prime d'assurance habitation est calculée",
        },
        {
          tag: "Finances personnelles",
          title: "Un guide pour ranger vos documents importants",
        },
      ],
      link: "Voir tous nos articles",
    },

    together: {
      title: "Ensemble, c'est mieux chez Desjardins",
      subTitle: "Premier groupe financier coopératif au Canada, nous travaillons ensemble pour un avenir meilleur.",
      youthTitle: "Engagés auprès des jeunes",
      youthText: "Plus de 50 millions de dollars chaque année pour aider les jeunes à réaliser leurs projets.",
      youthLink: "En savoir plus sur le programme Tous engagés pour la jeunesse",
      greenTitle: "Favoriser le développement durable",
      greenText: "Avec près de 50 options d'investissement responsable (IR).",
      greenLink: "En savoir plus sur notre démarche d'IR",
      memberTitle: "Devenir membre, c'est plus qu'ouvrir un compte",
      memberText1: "Chaque caisse Desjardins est une coopérative de services financiers. En tant que membre, vous participez aux décisions de la caisse, avez droit aux ",
      memberRistournes: "ristournes",
      memberText2: " et contribuez au mieux-être de votre milieu.",
      ready: "Prêt à faire le saut?",
      becomeMember: "Devenir membre",
    },

    contactUs: {
      title: "Nous joindre",
      phoneTitle: "Par téléphone",
      phoneSub: "Nous pouvons vous appeler au moment qui vous convient.",
      scheduleCall: "Planifier un appel",
      notes: "Notes",
      notesText1: "Les caisses Desjardins sont des institutions financières coopératives. Elles sont membres de la Fédération des caisses Desjardins du Québec et offrent des services financiers aux particuliers et aux entreprises.",
      notesText2: "Sous réserve de l'approbation du crédit. Des conditions s'appliquent. Consultez votre caisse pour plus de détails.",
    },

    footer: {
      usefulLinks: "Liens utiles",
      usefulList: [
        "Soutien en cas de difficultés financières",
        "Outils et calculateurs",
        "Taux",
        "Trouver une caisse",
        "Sécurité",
        "Carte perdue ou volée",
        "Changer d'adresse",
      ],
      helpContact: "Aide et contact",
      helpList: ["Centre d'aide", "Foire aux questions", "Nous joindre"],
      personal: "Particuliers",
      personalList: [
        "Comptes et services",
        "Cartes de crédit",
        "Hypothèque",
        "Prêts et crédit",
        "Épargne et placement",
        "Assurance",
        "Gestion de patrimoine",
        "Offres",
      ],
      business: "Entreprises",
      businessList: [
        "Comptes et gestion de trésorerie",
        "Financement et prêts",
        "Cartes de crédit",
        "Projets",
        "Secteurs d'activité",
        "Partenaires et solutions d'affaires",
        "Solutions pour employeurs",
        "Assurance",
        "Services internationaux",
        "Placement",
        "Marchés des capitaux",
        "Services de fiducie",
        "Régimes collectifs de retraite",
        "Rajoutez votre appareil de confiance",
      ],
      about: "À propos",
      careers: "Carrières",
      careersList: ["Travailler chez Desjardins", "Processus d'embauche", "Catégories d'emplois"],
      tips: "Conseils",
      news: "Nouvelles",
      advisorResources: "Ressources pour conseillers",
      followUs: "Suivez-nous",
      bottomLinks: [
        "Conditions d'utilisation et notes légales",
        "Politiques de confidentialité",
        "Personnaliser les témoins (cookies)",
        "Accessibilité",
        "Plan du site",
      ],
      copyright: "© 1996-2026, Fédération des caisses Desjardins du Québec. Tous droits réservés.",
    },

    login: {
      langSwitch: "English",
      contactUs: "Nous joindre",
      help: "Aide",
      backToDesjardins: "← Retour à Desjardins.com",
      title: "Se connecter à votre compte",
      usernameLabel: "Identifiant",
      rememberMe: "Se souvenir de moi",
      isSafe: "(Est-ce sécuritaire?)",
      passwordLabel: "Mot de passe",
      passwordImportant: "Important :",
      passwordCaseSensitive: "Le mot de passe est sensible à la casse.",
      forgotPassword: "Mot de passe oublié?",
      submitBtn: "Se connecter",
      submittingBtn: "Connexion...",
      useAnotherUsername: "Utiliser un autre identifiant",
      manageUsernames: "Gérer les identifiants",
      registerAccesD: "S'inscrire à AccèsD",
      registerAccesDAffaires: "S'inscrire à AccèsD Affaires",
      becomeMember: "Devenir membre",
      siteSecurity: "Sécurité du site",
      techSupport: "Soutien technique",
      reportFraud: "Signaler une fraude",
      guarantee: "Garantie",
      security100: "100 % sécurité",
      footerServicesPersonal: "SERVICES AUX PARTICULIERS",
      footerServicesBusiness: "SERVICES AUX ENTREPRISES",
      footerTips: "CONSEILS",
      footerAbout: "À PROPOS",
      footerMobileApp: "APPLICATION MOBILE",
      footerLinks: ["Sécurité", "Conditions d'utilisation et notes légales", "Confidentialité", "Personnaliser les témoins", "Accessibilité", "Plan du site"],
      footerCopyright: "© 1996-2026, Mouvement des caisses Desjardins - Groupe Desjardins. Tous droits réservés.",
    },
  },

  en: {
    nav: {
      about: "About us",
      careers: "Careers",
      tips: "Tips",
      contact: "Contact us",
      langBtn: "QC | English",
      chooseLang: "Choose your language",
      chooseProvince: "Choose your province or territory",
      confirm: "Confirm",
      personal: "Personal",
      business: "Business",
      personalItems: [
        "Accounts and services",
        "Credit cards",
        "Mortgages",
        "Loans and credit",
        "Savings and investment",
        "Insurance",
        "Wealth management",
        "Offers",
      ],
      businessItems: [
        { name: "Accounts and treasury management" },
        { name: "Financing and loans" },
        { name: "Credit cards" },
        { name: "Projects" },
        { name: "Business sectors" },
        { name: "Partners and business solutions" },
        { name: "Employer solutions" },
        { name: "Insurance" },
        { name: "International services" },
        { name: "Investment" },
        { name: "Capital markets" },
        { name: "Trust services", external: true },
        { name: "Group retirement plans" },
        { name: "See more", chevron: true },
      ],
      getHelp: "Get help",
      login: "Log in",
      loginModalTitle: "Log in",
      onlineServices: "Online services",
      access: "Log in",
      moreAccesD: "Learn more about AccèsD",
      moreAccesDAffaires: "Learn more about AccèsD Business",
      autoHomeInsurance: "Auto and home insurance",
      desjardinsInsurance: "Desjardins Insurance",
      onlineBrokerage: "Online brokerage",
      desjardinsDisnat: "Desjardins Disnat",
      securities: "Desjardins Securities",
      wealthManagement: "Wealth management",
      visitOtherSite: "Visit another Desjardins site",
      select: "Select",
      securityGuarantee: "Security guarantee",
    },

    hero: {
      tagline: "Committed. Connected.",
      title: "Moving to Canada?",
      text: "We're here to help you settle in with products and services tailored to your reality.",
      button: "Explore options for newcomers",
    },

    whatToDo: {
      title: "What would you like to do today?",
      cards: [
        "Compare credit cards",
        "Buy a home",
        "Get insurance",
        "Apply for a personal loan",
        "Learn more about our accounts and services",
        "Save and invest for the future",
      ],
    },

    alarmClock: {
      title: "Save for what matters with a TFSA",
      text: "Invest early and save more tax-free",
      link: "Discover all the benefits of a TFSA",
    },

    interestRates: {
      title: "Check our reference rates",
      text: "Learn more about exchange rates and rates for our savings, investment, and financing products.",
      link: "See current rates",
    },

    toolsCalculators: {
      title: "Popular tools and calculators",
      tools: [
        "Budgeting tool",
        "Mortgage borrowing capacity calculator",
        "Mortgage payment calculator",
        "Retirement calculator",
      ],
      link: "See all tools and calculators",
    },

    onlineAccess: {
      title: "Access your accounts online",
      text1: "The Desjardins Mobile Services app allows you to quickly access your accounts and keep an eye on your finances. Use it anytime, anywhere.",
      subTitle: "Here is what you can do:",
      items: [
        "Make transfers",
        "Pay bills",
        "Deposit cheques",
        "Place a stop payment",
        "View your statements and manage your accounts",
      ],
      text2: "You can also use the app for an overview of your insurance policies and to make investments.",
      link: "Discover our mobile services",
      appTitle: "Download the Desjardins Mobile Services app",
    },

    needHelp: {
      title: "Need help?",
      subTitle: "Let us guide you.",
      items: [
        "Report fraud",
        "Dispute a credit card transaction",
        "Make an insurance claim",
        "Browse the FAQ",
      ],
    },

    countOnUs: {
      title: "Advice you can rely on",
      subTitle: "Make informed decisions with our selection of articles.",
      articles: [
        {
          tag: "Insurance",
          title: "How home insurance premiums are calculated",
        },
        {
          tag: "Personal finance",
          title: "A guide to organizing your important documents",
        },
      ],
      link: "See all our articles",
    },

    together: {
      title: "Together, it's better at Desjardins",
      subTitle: "Canada's leading cooperative financial group, we work together for a better future.",
      youthTitle: "Committed to youth",
      youthText: "Over $50 million every year to help young people achieve their goals.",
      youthLink: "Learn more about the All Committed to Youth program",
      greenTitle: "Promoting sustainable development",
      greenText: "With nearly 50 responsible investment (RI) options.",
      greenLink: "Learn more about our RI approach",
      memberTitle: "Becoming a member is more than opening an account",
      memberText1: "Every Desjardins caisse is a financial services cooperative. As a member, you take part in caisse decisions, are entitled to ",
      memberRistournes: "member dividends",
      memberText2: " and contribute to the well-being of your community.",
      ready: "Ready to make the leap?",
      becomeMember: "Become a member",
    },

    contactUs: {
      title: "Contact us",
      phoneTitle: "By phone",
      phoneSub: "We can call you at a time that works for you.",
      scheduleCall: "Schedule a call",
      notes: "Notes",
      notesText1: "Desjardins caisses are cooperative financial institutions. They are members of the Fédération des caisses Desjardins du Québec and offer financial services to individuals and businesses.",
      notesText2: "Subject to credit approval. Conditions apply. Contact your caisse for details.",
    },

    footer: {
      usefulLinks: "Useful links",
      usefulList: [
        "Financial difficulty support",
        "Tools and calculators",
        "Rates",
        "Find a caisse",
        "Security",
        "Lost or stolen card",
        "Change address",
      ],
      helpContact: "Help and contact",
      helpList: ["Help centre", "Frequently asked questions", "Contact us"],
      personal: "Personal",
      personalList: [
        "Accounts and services",
        "Credit cards",
        "Mortgages",
        "Loans and credit",
        "Savings and investment",
        "Insurance",
        "Wealth management",
        "Offers",
      ],
      business: "Business",
      businessList: [
        "Accounts and treasury management",
        "Financing and loans",
        "Credit cards",
        "Projects",
        "Business sectors",
        "Partners and business solutions",
        "Employer solutions",
        "Insurance",
        "International services",
        "Investment",
        "Capital markets",
        "Trust services",
        "Group retirement plans",
        "Rajoutez votre appareil de confiance",
      ],
      about: "About us",
      careers: "Careers",
      careersList: ["Working at Desjardins", "Hiring process", "Job categories"],
      tips: "Tips",
      news: "News",
      advisorResources: "Advisor resources",
      followUs: "Follow us",
      bottomLinks: [
        "Terms of Use and Legal Notes",
        "Privacy Policies",
        "Customize Cookies",
        "Accessibility",
        "Site Map",
      ],
      copyright: "© 1996-2026, Fédération des caisses Desjardins du Québec. All rights reserved.",
    },

    login: {
      langSwitch: "Français",
      contactUs: "Contact us",
      help: "Help",
      backToDesjardins: "← Back to Desjardins.com",
      title: "Log in to your account",
      usernameLabel: "Username",
      rememberMe: "Remember me",
      isSafe: "(Is it safe?)",
      passwordLabel: "Password",
      passwordImportant: "Important:",
      passwordCaseSensitive: "The password is case-sensitive.",
      forgotPassword: "Forgot password?",
      submitBtn: "Log in",
      submittingBtn: "Logging in...",
      useAnotherUsername: "Use another username",
      manageUsernames: "Manage usernames",
      registerAccesD: "Sign up for AccèsD",
      registerAccesDAffaires: "Sign up for AccèsD Business",
      becomeMember: "Become a member",
      siteSecurity: "Site security",
      techSupport: "Technical support",
      reportFraud: "Report fraud",
      guarantee: "Guarantee",
      security100: "100% security",
      footerServicesPersonal: "PERSONAL SERVICES",
      footerServicesBusiness: "BUSINESS SERVICES",
      footerTips: "TIPS",
      footerAbout: "ABOUT US",
      footerMobileApp: "MOBILE APP",
      footerLinks: ["Security", "Terms of Use and Legal Notes", "Privacy", "Customize Cookies", "Accessibility", "Site Map"],
      footerCopyright: "© 1996-2026, Desjardins Group. All rights reserved.",
    },
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("fr");

  const t = translations[lang] || translations.fr;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
